package carrental;
// Generated May 1, 2018 2:30:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Customerbookings generated by hbm2java
 */
public class Customerbookings  implements java.io.Serializable {


     private Integer bookingId;
     private Cars cars;
     private Customers customers;
     private Date bookingDate;
     private int timePeriod;
     private String status;

    public Customerbookings() {
    }

    public Customerbookings(Cars cars, Customers customers, Date bookingDate, int timePeriod, String status) {
       this.cars = cars;
       this.customers = customers;
       this.bookingDate = bookingDate;
       this.timePeriod = timePeriod;
       this.status = status;
    }
   
    public Integer getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(Integer bookingId) {
        this.bookingId = bookingId;
    }
    public Cars getCars() {
        return this.cars;
    }
    
    public void setCars(Cars cars) {
        this.cars = cars;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(Date bookingDate) {
        this.bookingDate = bookingDate;
    }
    public int getTimePeriod() {
        return this.timePeriod;
    }
    
    public void setTimePeriod(int timePeriod) {
        this.timePeriod = timePeriod;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


