package carrental;
// Generated May 1, 2018 2:30:41 PM by Hibernate Tools 4.3.1



/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer id;
     private String staffname;
     private String name;
     private String password;
     private String contactNo;
     private String email;
     private String address;

    public Staff() {
    }

    public Staff(String staffname, String name, String password, String contactNo, String email, String address) {
       this.staffname = staffname;
       this.name = name;
       this.password = password;
       this.contactNo = contactNo;
       this.email = email;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStaffname() {
        return this.staffname;
    }
    
    public void setStaffname(String staffname) {
        this.staffname = staffname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


